#!/bin/bash

# Enter the remote server's IP address or domain name
remote_server="remote_server_ip_or_domain_name"

# Enter the remote server's username
remote_user="remote_username"

# Enter the remote file path and name
remote_file="/path/to/remote/file"

# Enter the local file path and name
local_file="/path/to/local/file"

# Enter the password for the remote server
password="password_here"

# Use scp command to transfer the file from remote server to local
echo $password | scp $remote_user@$remote_server:$remote_file $local_file

# Verify if the file transfer is successful
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
